"""changed gender data type

Revision ID: 0271ffb70d0f
Revises: 440717fdd550
Create Date: 2022-01-31 14:03:48.221320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0271ffb70d0f'
down_revision = '440717fdd550'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
     op.alter_column('users', 'gender',
                existing_type=sa.VARCHAR(),
                type_=sa.Integer(),
                existing_nullable=True,
               postgresql_using='gender::integer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
