"""добавил ограничение на уникальность

Revision ID: 2019286d1c95
Revises: 690fd89f51eb
Create Date: 2022-02-02 13:11:40.619715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2019286d1c95'
down_revision = '690fd89f51eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'who_liked_who', ['who', 'liked_who'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'who_liked_who', type_='unique')
    # ### end Alembic commands ###
