"""добавил who seen who

Revision ID: 2b567f11a62d
Revises: b61f873e8a39
Create Date: 2022-02-02 11:08:54.719798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b567f11a62d'
down_revision = 'b61f873e8a39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('who_seen_who',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('who', sa.Integer(), nullable=True),
    sa.Column('seen_who', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['who'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_who_seen_who_who'), 'who_seen_who', ['who'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_who_seen_who_who'), table_name='who_seen_who')
    op.drop_table('who_seen_who')
    # ### end Alembic commands ###
