"""добавил уведомления лайков

Revision ID: 3a6b923ee14e
Revises: 4582dd8e8050
Create Date: 2022-02-08 22:19:26.825948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a6b923ee14e'
down_revision = '4582dd8e8050'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('who_liked_who', sa.Column('liked_person_notificated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('who_liked_who', 'liked_person_notificated')
    # ### end Alembic commands ###
