"""добавил каскад

Revision ID: 4582dd8e8050
Revises: b98837086501
Create Date: 2022-02-08 21:59:17.825412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4582dd8e8050'
down_revision = 'b98837086501'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('who_liked_who_who_fkey', 'who_liked_who', type_='foreignkey')
    op.create_foreign_key(None, 'who_liked_who', 'users', ['who'], ['uid'], ondelete='CASCADE')
    op.drop_constraint('who_seen_who_who_fkey', 'who_seen_who', type_='foreignkey')
    op.create_foreign_key(None, 'who_seen_who', 'users', ['who'], ['uid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'who_seen_who', type_='foreignkey')
    op.create_foreign_key('who_seen_who_who_fkey', 'who_seen_who', 'users', ['who'], ['uid'])
    op.drop_constraint(None, 'who_liked_who', type_='foreignkey')
    op.create_foreign_key('who_liked_who_who_fkey', 'who_liked_who', 'users', ['who'], ['uid'])
    # ### end Alembic commands ###
