"""поправил repr who liked who

Revision ID: 4e86b28ce548
Revises: eb7ea59f2a13
Create Date: 2022-02-02 13:48:57.180734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e86b28ce548'
down_revision = 'eb7ea59f2a13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
