"""добавил who liked  who

Revision ID: 690fd89f51eb
Revises: 2b567f11a62d
Create Date: 2022-02-02 12:45:51.426425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '690fd89f51eb'
down_revision = '2b567f11a62d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('who_liked_who',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('who', sa.Integer(), nullable=True),
    sa.Column('liked_who', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['who'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_who_liked_who_who'), 'who_liked_who', ['who'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_who_liked_who_who'), table_name='who_liked_who')
    op.drop_table('who_liked_who')
    # ### end Alembic commands ###
