"""добавил поле has_seen

Revision ID: 751a55e432c2
Revises: 0271ffb70d0f
Create Date: 2022-02-01 20:13:12.260690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '751a55e432c2'
down_revision = '0271ffb70d0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
