"""реально добавил поле has seen

Revision ID: b61f873e8a39
Revises: 751a55e432c2
Create Date: 2022-02-01 20:15:05.210800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b61f873e8a39'
down_revision = '751a55e432c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('has_seen', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'has_seen')
    # ### end Alembic commands ###
