"""добавил ограничение на уникальность 2

Revision ID: eb7ea59f2a13
Revises: 2019286d1c95
Create Date: 2022-02-02 13:13:41.446163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb7ea59f2a13'
down_revision = '2019286d1c95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'who_seen_who', ['who', 'seen_who'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'who_seen_who', type_='unique')
    # ### end Alembic commands ###
